export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  GATE_BLOCKED: "GATE_BLOCKED",
  EXCEPTION_REASON_REQUIRED: "EXCEPTION_REASON_REQUIRED",
  EXCEPTION_EXPIRES_REQUIRED: "EXCEPTION_EXPIRES_REQUIRED",
  DOCUMENT_PARSE_EMPTY: "DOCUMENT_PARSE_EMPTY",
  SNAPSHOT_FROZEN: "SNAPSHOT_FROZEN"
} as const;
