export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  GATE_BLOCKED: "GATE_BLOCKED",
  EXCEPTION_INCOMPLETE: "EXCEPTION_INCOMPLETE",
  ALREADY_RELEASED: "ALREADY_RELEASED",
  NO_CANDIDATE_VERSION: "NO_CANDIDATE_VERSION"
} as const;
